# Generated by Django 5.1 on 2024-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
