# Generated by Django 5.1 on 2024-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_internshipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(upload_to='assets/files/'),
        ),
    ]
