# Generated by Django 5.1 on 2024-08-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_internshipapplication_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills',
        ),
    ]
