# Generated by Django 5.1 on 2024-08-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_aboutus_options_alter_aboutus_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='images',
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.aboutus')),
            ],
        ),
    ]
