# Generated by Django 5.1 on 2024-08-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_aboutusimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
