# Generated by Django 5.1 on 2024-08-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_aboutus_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='AboutUsImage',
            new_name='MenuImage',
        ),
    ]
