# Generated by Django 5.1 on 2024-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_pinenewscategories_pinenewstags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinenews',
            options={'verbose_name_plural': 'Pine News'},
        ),
        migrations.AlterModelOptions(
            name='pinenewscategories',
            options={'verbose_name_plural': 'Pine News Categories'},
        ),
        migrations.AlterModelOptions(
            name='pinenewstags',
            options={'verbose_name_plural': 'Pine News Tags'},
        ),
        migrations.AddField(
            model_name='pinenews',
            name='image',
            field=models.ImageField(default='', upload_to='assets/images'),
        ),
    ]
