# Generated by Django 5.1 on 2024-08-30 04:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_pinenews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenews',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
