# Generated by Django 5.1 on 2024-08-30 10:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_pinenews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinenews',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
        ),
    ]
