# Generated by Django 5.1 on 2024-08-31 06:55

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_pinenews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenews',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
