# Generated by Django 5.1 on 2024-09-02 05:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_pinenews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenews',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
