# Generated by Django 5.1 on 2024-09-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_pinenews_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinenews',
            old_name='image',
            new_name='images',
        ),
    ]
