# Generated by Django 5.1 on 2024-09-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenewsimage',
            name='pine_news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.pinenews'),
        ),
    ]
