# Generated by Django 5.1 on 2024-09-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_pinenewsimage_pine_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenewsimage',
            name='pine_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.pinenews'),
        ),
    ]
