# Generated by Django 5.1 on 2024-09-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_pinenewsimage_pine_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PineNewsImage',
        ),
    ]
